-- Lisää DROP TABLE lauseet tähän tiedostoon
   DROP TABLE IF EXISTS TASKS CASCADE;
   
   DROP TABLE IF EXISTS USERS CASCADE;
   
   DROP TABLE IF EXISTS CATEGORIES CASCADE;
   
   DROP TABLE IF EXISTS TASK_CATEGORY CASCADE;
